export const FPS = 50
export const INITIAL_VEL_MULIPLIER = 100
export const BASE_VELOCITY_X_RANGE = 1
export const BASE_VELOCITY_Y_RANGE = 1
export const MIN_SIZE_POINTS = 5
export const MAX_SIZE_POINTS = 15
export const POINTS_BOUNCE = true
export const HOVER_VELOCITY_MULTIPLIER = 1.1
export const MAX_HOVER_VELOCITY = HOVER_VELOCITY_MULTIPLIER * 5 // MAX_HOVER_VELOCITY must be always a multiple of HOVER_VELOCITY_MULTIPLIER so the pount can return to its original velocity
